config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contents#index'
  resources :contents, only:[:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :choices do
    resources :votes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :content
  has_many :votes, dependent: :destroy
  has_one_attached :image

  validates :text_or_image, presence: true

  def text_or_image
    text.presence or image.presence
  end

  def vote_user(user_id)
    votes.find_by(user_id: user_id)
  end
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_many :choices, dependent: :destroy
  has_many :votes, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true

  validates_associated :choices

  with_options presence: true do
    validates :title
    validates :user
  end

  def self.search(search)
    if search != ""
      Content.where('title LIKE(?)', "%#{search}%")
    else
      Content.all
    end
  end
end
  

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents
  has_many :votes

  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}\z/i, message: 'は半角英数字混合で入力してください' }
  validates :password_confirmation, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}\z/i, message: 'は半角英数字混合で入力してください' }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :content
  belongs_to :choice, counter_cache: :votes_count

  validates :choice, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD'] # 環境変数を読み込む記述に変更
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.includes(:user, :choices).order('created_at DESC')
  end

  def new
    @content = Content.new

    # あらかじめ2つの項目入力欄を表示しておく為。
    2.times { @content.choices.build }

  end

  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @content = current_user.contents.find(params[:id])
  end

  def update
    content = current_user.contents.find(params[:id])
    if content.update(content_params)
    else
      render :edit
    end
  end

  def destroy
    content = current_user.contents.find(params[:id])
    if content.destroy
    else
      render :index
    end
  end

  def search
    @contents = Content.search(params[:keyword])
  end

  private

  def content_params
    params.require(:content)
          .permit(:title, choices_attributes: [:id, :text, :image, :content_id, :_destroy])
          .merge(user_id: current_user.id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_choice

  def create
    @vote = Vote.new(vote_params)
    already_vote(@vote).destroy if overlap_adjustment?(@vote)
    @vote.save

    # choiceの再セット
    @choice.reload
    @choices = @choice.content.choices
  end

  def destroy
    vote = Vote.find_by(vote_params)
    vote.destroy
    @choice.reload
  end

  private

  def vote_params
    params.permit(id: @choice.id).merge(user_id: current_user.id, content_id: @choice.content_id, choice_id: @choice.id)
  end

  def set_choice
    @choice = Choice.find(params[:id])
  end

  def overlap_adjustment?(vote)
    is_exist_already_vote = already_vote(vote)&.user_id == current_user.id
    is_exist_content_vote = already_vote(vote)&.content_id
    return is_exist_already_vote && is_exist_content_vote
  end

  def already_vote(vote)
    already_votes = @choice.content.votes
    if already_votes.nil?
      return nil
    end
    already_vote = already_votes.find_by(user_id: vote.user_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages
    return '' if resource.errors.empty?

    html = ''
    messages = resource.errors.full_messages.each do |msg|
      html += <<-EOF
        <div class="error_field alert alert-danger" role="alert">
          <p class="error_msg">#{msg}</p>
        </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/contents/_choices_fields.html.haml
.nested-fields
  .nested-fields__form
    .nested-fields__form__text
      = f.text_field :text, class: 'choice-form', placeholder: '例 : ホワイト or ブラック'
    .nested-fields__form__image
      = f.label :image, class: "input-box__image" do
        = icon('far', 'image', class: 'form-icon')
        = f.file_field :image, class: "hidden"
  = link_to_remove_association "✖️", f, class: 'delete', id: 'remove-btn'

app/views/contents/_content.html.haml
.main__contents.input
  - @contents.each do |content|
    .main__contents__content.input__new
      - if user_signed_in?
        - if current_user.id == content.user_id
          .more
            = icon("fas", "angle-down")
            %ul.more_list
              %li
                = link_to '編集', edit_content_path(content.id), method: :get
                = link_to '削除', content_path(content.id), method: :delete
        - else
      -else
      .main__contents__content__title
        = content.title
      .main__contents__content__choices
        - content.choices.each do |choice|
          .main__contents__content__choices__choice
            - if choice.text.present?
              .main__contents__content__choices__choice__text
                = choice.text 
            .main__contents__content__choices__choice__image
              = image_tag choice.image.variant(resize: '200x200') if choice.image.present?
            .main__contents__content__choices__choice__number
              .main__contents__content__choices__choice__number__vote#vote{id: choice.id}
                = render partial: "vote", locals: { choice: choice }
      .main__contents__content__info
        .main__contents__content__info__name
          = content.user.nickname
        .main__contents__content__info__date
          = content.created_at.strftime("%Y-%m-%d %H:%M")

app/views/contents/_vote.html.haml
- if user_signed_in?
  - if choice.vote_user(current_user.id)
    = button_to choice_vote_path(id: choice.id, choice_id: choice.id), method: :delete, id: "vote-btn", remote: true do
      = icon("fas", "heart")
      %span
        = choice.votes_count
        
  - else
    = button_to choice_votes_path(id: choice.id, choice_id: choice.id), id: "vote-btn", remote: true do
      = icon("far", "heart")
      %span
        = choice.votes_count
- else
  #vote-btn
    = icon("far", "heart")
    %span
      = choice.votes_count

app/views/contents/destroy.html.haml
.input
  .input__new
    %h3
      削除が完了しました。
    .to-toppage
      = link_to 'トップページへ戻る', root_path, class: "submit"

app/views/contents/edit.html.haml
.input
  .input__new
    = form_with model: @content, url: content_path(@content.id), local: true do |f|
      .title
        お題を編集する
      = render "shared/error_messages", model: f.object
      .input__new__title
        = f.label :title
        = f.text_field :title, class: 'title-form', placeholder: "例 : スマホ買い換えるなら、色は？"
      .input__new__choices
        .input__new__choices__choice
          みんなに選んでもらう項目をきめてね！(2つ以上入力)
        = f.label :text
        = f.fields_for :choices do |c|
          = render "choices_fields", f: c
        .links
          = link_to_add_association "➕", f, :choices, class: 'add', partial: "choices_fields", data: {association_insertion_method: 'before'}
      = f.submit "編集完了！", class: 'submit'

app/views/contents/index.html.haml
.wrapper
  = render "shared/search_form"
  = render "content"

app/views/contents/new.html.haml
.input
  .input__new
    = form_with model: @content, url: contents_path, local: true do |f|
      .title
        みんなに投票してもらおう！
      = render "shared/error_messages", model: f.object
      .input__new__title
        = f.label :title
        = f.text_field :title, class: 'title-form', placeholder: "例 : スマホ買い換えるなら、色は？"
      .input__new__choices
        .input__new__choices__choice
          みんなに選んでもらう項目をきめてね！(2つ以上入力)
        = f.label :text
        = f.fields_for :choices do |c|
          = render "choices_fields", f: c
        .links
          = link_to_add_association "➕", f, :choices, class: 'add', partial: "choices_fields", data: {association_insertion_method: 'before'}
      = f.submit "さっそく聞いてみる！", class: 'submit'

app/views/contents/search.html.haml
= render "shared/search_form"
= @contents.each do |content|
  = render partial: "content", locals: { content: content }

app/views/contents/update.html.haml
.input
  .input__new
    %h3
      更新が完了しました。
    .to-toppage
      = link_to 'トップページへ戻る', root_path, class: "submit"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Voting
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .header__logo
        = icon("fas", "vote-yea") 
        = link_to "Voting.me", root_path, class: "header__logo"
      - if user_signed_in? 
        .header__user
          .name
            = icon("fas", "user")
            = current_user.nickname
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post"
          = link_to "投票を決める", new_content_path, class: "post"
      - else
        .header__user
          = link_to "ログイン", new_user_session_path, class: "post"
          = link_to "新規登録", new_user_registration_path, class: "post"
    = yield
    .footer
      Voting.me 2020

app/views/shared/_error_messages.html.haml
- if model.errors.any?
  .error-alert
    %ul 
      - model.errors.full_messages.each do |message|
        %li= message

app/views/shared/_search_form.html.haml
= form_with url: search_contents_path, local: true, method: :get, class: "search-form" do |f|
  = f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input title-form"
  = f.submit "検索", class: "search-btn submit"

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/votes/create.js.haml
- @choices.each do |choice|

  $("#vote_#{choice.id}").html("#{j(render partial: 'contents/vote', locals: {id: choice.id, choice: choice})}");

app/views/votes/destroy.js.haml
$("#vote_#{@choice.id}").html("#{j(render partial: 'contents/vote', locals: {id: @choice.id, choice: @choice}) }")